eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8081


spring:
  application:
    name: farmers
  config:
    import: optional:configserver:http://localhost:8888
  # datasource:
  #   url: jdbc:postgresql://localhost:5432/farmers
  #   username: root
  #   password: root
  #   driver-class-name: org.postgresql.Driver
  # jpa:
  #   hibernate:
  #     ddl-auto: update
  #   database: postgresql
  #   database-platform: org.hibernate.dialect.PostgreSQLDialect